-- QUERY PARA AJUSTAR RETORNO DE SEPARAÇÃO DE LOTES DO WMS

DECLARE @SELECAO(VARCHAR 10)
SET @SELECAO = '' --INSERIR LOTE
		BEGIN TRAN

			UPDATE A 
			SET A.QTDE_EMBALADA = B.QTDE_EMBALADA
			FROM TB_PROD_EMBALADO AS A
				JOIN TB_RETORNO_ES AS B
					ON A.SELECAO = B.LOTE
					AND A.PEDIDO = B.PEDIDO
					AND A.PRODUTO = B.PRODUTO
					AND A.COR_PRODUTO = B.COR_PRODUTO
					AND A.ROMANEIO = B.ROMANEIO 
				WHERE A.SELECAO = @SELECAO
