/* PARA ALTERAR OS LOTES, BASTA SELECIONAR O MESMO NA SEGUNDA CONDIÇÃO DO WHERE */
SELECT  
    CASE
        WHEN SEL.SELECAO_CROSS IS NOT NULL AND SEL.STATUS_PROCESSO = 3 
            THEN 16
        WHEN B.LIBERADO_SEPARACAO = 0 
             AND (SEL.SELECAO_CROSS_STATUS IS NULL OR SEL.STATUS_PROCESSO > 3) 
            THEN 1
        WHEN B.LIBERADO_SEPARACAO = 1 AND B.PROCESSADO = 0 
             AND (SEL.SELECAO_CROSS_STATUS IS NULL OR SEL.STATUS_PROCESSO > 3) 
            THEN 2
        WHEN B.PROCESSADO = 1 
             AND A.CAIXA IS NULL 
             AND F.LOTE IS NULL 
             AND ISNULL(B.COLETOR, 0) = 0 
             AND ISNULL(B.SORTER, 0) = 0 
             AND (SEL.SELECAO_CROSS_STATUS IS NULL OR SEL.STATUS_PROCESSO > 3) 
            THEN 3
        WHEN A.CAIXA IS NOT NULL AND A.CAIXA_FECHADA = 1 
             AND (SEL.SELECAO_CROSS_STATUS IS NULL OR SEL.STATUS_PROCESSO > 3) 
            THEN 4
        WHEN A.CAIXA IS NULL AND F.LOTE IS NOT NULL 
             AND (SEL.SELECAO_CROSS_STATUS IS NULL OR SEL.STATUS_PROCESSO > 3) 
            THEN 5
        WHEN SEL.SELECAO_CROSS IS NOT NULL AND SEL.STATUS_PROCESSO = 2 
             AND (SEL.SELECAO_CROSS_STATUS < 4 OR SEL.SELECAO_CROSS_STATUS = 5) 
             AND ISNULL(RTRIM(LTRIM(SEL.CAIXA_CROSS)),'') = '' 
            THEN SEL.SELECAO_CROSS_STATUS + 10
        WHEN SEL.SELECAO_CROSS IS NOT NULL AND SEL.STATUS_PROCESSO = 2 
             AND SEL.SELECAO_CROSS_STATUS >= 4 
             AND ISNULL(RTRIM(LTRIM(SEL.CAIXA_CROSS)),'') <> '' 
            THEN SEL.SELECAO_CROSS_STATUS + 10
        WHEN SEL.SELECAO_CROSS IS NOT NULL AND SEL.STATUS_PROCESSO = 2 
             AND SEL.SELECAO_CROSS_STATUS >= 4 
             AND ISNULL(RTRIM(LTRIM(SEL.CAIXA_CROSS)),'') = '' 
            THEN SEL.SELECAO_CROSS_STATUS + 9
    END AS STATUS_LOG,



    CASE
        WHEN B.LIBERADO_SEPARACAO = 0 
            THEN 'AGUARDANDO LIBERACAO'
        WHEN B.LIBERADO_SEPARACAO = 1 AND B.PROCESSADO = 0 
            THEN 'AGUARDANDO ENVIO/IMPRESSAO'
        WHEN B.PROCESSADO = 1 AND A.CAIXA IS NULL AND F.LOTE IS NULL 
            THEN 'EM SEPARACAO'
        WHEN A.CAIXA IS NOT NULL AND A.CAIXA_FECHADA = 1 
            THEN 'LIBERADO PARA FATURAMENTO'
        WHEN A.CAIXA IS NULL AND F.LOTE IS NOT NULL 
            THEN 'DIVERGENTE'
    END AS DESC_STATUS_LOG,

    E.TIPO_OPERACAO AS TIPO,
    A.NOME_CLIFOR,
    A.FILIAL,
    A.SELECAO,
    SEL.SELECAO_CROSS,
    CRS.SELECAO AS SELECAO_ORIGEM,
    SEL.SELECAO_CROSS_STATUS,
    SEL.STATUS_PROCESSO,
    CRS.SELECAO_CROSS,
    CASE WHEN A.CAIXA IS NOT NULL THEN 'CX. OK' ELSE NULL END AS CAIXA,
    SUM(A.QTDE_EMBALADA) AS QTDE,
    SUM(A.VALOR_EMBALADO) AS VALOR,
    D.REGIAO,
    C.REPRESENTANTE,
    D.SEM_CREDITO,
    D.TIPO_BLOQUEIO,
    C.TIPO AS TIPO_FATURAMENTO,
    CONVERT(DATETIME, CONVERT(CHAR(10), B.DATA_CRIACAO, 112)) AS DATA_CRIACAO,
    B.USUARIO AS USUARIO_CRIACAO,
    CONVERT(DATETIME, CONVERT(CHAR(10), G.DATA_LIBERACAO, 112)) AS DATA_LIBERACAO,
    G.USUARIO AS USUARIO_LIBERACAO,
    PROD.REDE_LOJAS,
    CONVERT(VARCHAR(150), '') AS STATUS_LOTE,
    B.COD_TRANSACAO,
    TROCA_ETIQ = MAX(CASE WHEN I.COLECAO IS NOT NULL THEN 1 ELSE 0 END)



FROM VENDAS_PROD_EMBALADO A
    JOIN TB_SELECAO B 
        ON A.PEDIDO = B.PEDIDO 
       AND A.ROMANEIO = B.ROMANEIO 
       AND A.PRODUTO = B.PRODUTO 
       AND A.COR_PRODUTO = B.COR_PRODUTO 
       AND A.ENTREGA = B.ENTREGA 
       AND A.SELECAO = CONVERT(CHAR(8), B.SELECAO)
    JOIN VENDAS C 
        ON A.PEDIDO = C.PEDIDO
    JOIN CLIENTES_ATACADO D 
        ON A.NOME_CLIFOR = D.CLIENTE_ATACADO
    JOIN CLIENTE_ATAC_TIPOS E 
        ON D.TIPO = E.TIPO
    JOIN PRODUTOS PROD 
        ON A.PRODUTO = PROD.PRODUTO
    LEFT JOIN (SELECT DISTINCT LOTE FROM TB_RETORNO_ES WHERE LOTE = '8371567') F 


        ON B.SELECAO = F.LOTE
    LEFT JOIN TB_PROD_EMBALADO G 
        ON A.PEDIDO = G.PEDIDO 
       AND A.ROMANEIO = G.ROMANEIO 
       AND A.PRODUTO = G.PRODUTO 
       AND A.COR_PRODUTO = G.COR_PRODUTO 
       AND A.ENTREGA = G.ENTREGA 
       AND A.SELECAO = CONVERT(CHAR(8), G.SELECAO) 
       AND A.ITEM = G.ITEM
    LEFT JOIN COLECOES I 
        ON PROD.COLECAO = I.COLECAO 
       AND I.ANO_COLECAO <= '2020'
    LEFT JOIN VW_TB_PROCESSO_CROSS SEL 
        ON A.SELECAO = SEL.SELECAO
    LEFT JOIN VW_TB_PROCESSO_CROSS CRS 
        ON A.SELECAO = CRS.SELECAO_CROSS


WHERE 1 = 1
AND A.SELECAO IN ('8373771 ','8371567 ')
GROUP BY
    CASE
        WHEN SEL.SELECAO_CROSS IS NOT NULL AND SEL.STATUS_PROCESSO = 3 
            THEN 16
        WHEN B.LIBERADO_SEPARACAO = 0 
             AND (SEL.SELECAO_CROSS_STATUS IS NULL OR SEL.STATUS_PROCESSO > 3) 
            THEN 1
        WHEN B.LIBERADO_SEPARACAO = 1 AND B.PROCESSADO = 0 
             AND (SEL.SELECAO_CROSS_STATUS IS NULL OR SEL.STATUS_PROCESSO > 3) 
            THEN 2
        WHEN B.PROCESSADO = 1 
             AND A.CAIXA IS NULL 
             AND F.LOTE IS NULL 
             AND ISNULL(B.COLETOR, 0) = 0 
             AND ISNULL(B.SORTER, 0) = 0 
             AND (SEL.SELECAO_CROSS_STATUS IS NULL OR SEL.STATUS_PROCESSO > 3) 
            THEN 3
        WHEN A.CAIXA IS NOT NULL AND A.CAIXA_FECHADA = 1 
             AND (SEL.SELECAO_CROSS_STATUS IS NULL OR SEL.STATUS_PROCESSO > 3) 
            THEN 4
        WHEN A.CAIXA IS NULL AND F.LOTE IS NOT NULL 
             AND (SEL.SELECAO_CROSS_STATUS IS NULL OR SEL.STATUS_PROCESSO > 3) 
            THEN 5
        WHEN SEL.SELECAO_CROSS IS NOT NULL AND SEL.STATUS_PROCESSO = 2 
             AND (SEL.SELECAO_CROSS_STATUS < 4 OR SEL.SELECAO_CROSS_STATUS = 5) 
             AND ISNULL(RTRIM(LTRIM(SEL.CAIXA_CROSS)),'') = '' 
            THEN SEL.SELECAO_CROSS_STATUS + 10
        WHEN SEL.SELECAO_CROSS IS NOT NULL AND SEL.STATUS_PROCESSO = 2 
             AND SEL.SELECAO_CROSS_STATUS >= 4 
             AND ISNULL(RTRIM(LTRIM(SEL.CAIXA_CROSS)),'') <> '' 
            THEN SEL.SELECAO_CROSS_STATUS + 10
        WHEN SEL.SELECAO_CROSS IS NOT NULL AND SEL.STATUS_PROCESSO = 2 
             AND SEL.SELECAO_CROSS_STATUS >= 4 
             AND ISNULL(RTRIM(LTRIM(SEL.CAIXA_CROSS)),'') = '' 
            THEN SEL.SELECAO_CROSS_STATUS + 9
    END,

    CASE
        WHEN B.LIBERADO_SEPARACAO = 0 
            THEN 'AGUARDANDO LIBERACAO'
        WHEN B.LIBERADO_SEPARACAO = 1 AND B.PROCESSADO = 0 
            THEN 'AGUARDANDO ENVIO/IMPRESSAO'
        WHEN B.PROCESSADO = 1 AND A.CAIXA IS NULL AND F.LOTE IS NULL 
            THEN 'EM SEPARACAO'
        WHEN A.CAIXA IS NOT NULL AND A.CAIXA_FECHADA = 1 
            THEN 'LIBERADO PARA FATURAMENTO'
        WHEN A.CAIXA IS NULL AND F.LOTE IS NOT NULL 
            THEN 'DIVERGENTE'
    END,
    E.TIPO_OPERACAO,
    A.NOME_CLIFOR,
    A.FILIAL,
    A.SELECAO,
    SEL.SELECAO_CROSS,
    CRS.SELECAO,
    SEL.SELECAO_CROSS_STATUS,
    SEL.STATUS_PROCESSO,
    CRS.SELECAO_CROSS,
    CASE WHEN A.CAIXA IS NOT NULL THEN 'CX. OK' ELSE NULL END,
    D.REGIAO,
    C.REPRESENTANTE,
    D.SEM_CREDITO,
    D.TIPO_BLOQUEIO,
    C.TIPO,
    CONVERT(DATETIME, CONVERT(CHAR(10), B.DATA_CRIACAO, 112)),
    B.USUARIO,
    CONVERT(DATETIME, CONVERT(CHAR(10), G.DATA_LIBERACAO, 112)),
    G.USUARIO,
    PROD.REDE_LOJAS,
    B.COD_TRANSACAO;
